    
    create table objetivo (
       id int8 generated by default as identity,
        data timestamp not null,
        titulo varchar(255) not null,
        usuario_id int8 not null,
        primary key (id)
    );
    
    create table perfil (
       usuario_id int8 not null,
        perfis varchar(7) not null
    );
    
    create table tarefa (
       id int8 generated by default as identity,
        is_feita boolean not null,
        titulo varchar(255) not null,
        objetivo_id int8 not null,
        primary key (id)
    );
    
    create table usuario (
       id int8 generated by default as identity,
        data_criacao_conta timestamp not null,
        email varchar(255) not null unique,
        nome varchar(255) not null,
        senha varchar(255) not null,
        primary key (id)
    );
    
    alter table if exists objetivo 
       add constraint fk_objetivo_usuario_id 
       foreign key (usuario_id) 
       references usuario;
    
    alter table if exists perfil 
       add constraint fk_perfil_usuario_id 
       foreign key (usuario_id) 
       references usuario;
    
    alter table if exists tarefa 
       add constraint fk_tarefa_objetivo_id 
       foreign key (objetivo_id) 
       references objetivo;