 create table anotacao (
       id int8 generated by default as identity,
	    titulo varchar(255) not null,
	    conteudo text,
        data_criacao timestamp not null,
	    data_modificacao timestamp not null,
	    usuario_id int8 not null,
        primary key (id)
);

alter table if exists anotacao 
       add constraint fk_anotacao_usuario_id 
       foreign key (usuario_id) 
       references usuario;