 create table feedback (
       id int8 generated by default as identity,
	    feedback text not null,
        data timestamp not null,
	    usuario_id int8 not null,
        primary key (id)
);

alter table if exists feedback 
       add constraint fk_feedback_usuario_id 
       foreign key (usuario_id) 
       references usuario;