create table artigo (
       id int8 generated by default as identity,
        titulo varchar(255) not null unique,
        avatar_url text not null,
        autor varchar(255) not null,
	    descricao varchar(255) not null,
        conteudo text not null,
		data_publicacao timestamp not null,
		data_atualizacao timestamp not null,
        categoria_id int8 not null,
        primary key (id)
    );
	
	 alter table if exists artigo 
       add constraint fk_artigo_categoria_id 
       foreign key (categoria_id) 
       references categoria;